### ISSUE TITLE
Add expense

### ISSUE THREAD

**Issue by camilldesmoulins** [TeamFrom306/expense-tracker#3]

**Comment by prokop7** [comment]
> Send page with form

What the heck? Explain

**Comment by camilldesmoulins** [comment]
@prokop7 
It means "Send HTML form for adding new expense to user"

**Comment by prokop7** [comment]
@camilldesmoulins 
That doesn't make any sense because we don't send a HTML page. We are exchanging data by JSON. That's a purpose of the front-end side.
