### ISSUE TITLE
WTF is that?

### ISSUE THREAD

**Issue by Raiondesu** [TeamFrom306/expense-tracker#7]
WTF is going on here?
Could anybody, please, explain?..

**Comment by camilldesmoulins** [comment]
We are working on a project

**Comment by Raiondesu** [comment]
@camilldesmoulins, well, this is quite obvious.
But what is the project's purpose?
Who are "ww"?
What do I have to do with all that?

**Comment by camilldesmoulins** [comment]
@Raiondesu 
Course project.
Anton an Me.
Do not disturb us) We decided to create the project in this organisation)

**Comment by Raiondesu** [comment]
Okay.
Got it.
